PROG1 = part1.scala
PROG2 = part2.scala

test1:
	scala-cli run $(PROG1) < test1.txt

run1:
	scala-cli run $(PROG1) < input.txt

test2:
	scala-cli run $(PROG2) < test1.txt

run2:
	scala-cli run $(PROG2) < input.txt

