PROG1 = part1.py
PROG2 = part2.py

default: test2

test1:
	./$(PROG1) < test1.txt

test1-2:
	./$(PROG1) < test2.txt

run1:
	./$(PROG1) < input.txt

test2:
	./$(PROG2) < test1.txt

test2-2:
	./$(PROG2) < test2.txt

run2:
	./$(PROG2) < input.txt
