PROG1 = part1.py
PROG2 = part2.py

test1:
	./$(PROG1) < test1.txt

test2:
	./$(PROG1) < test2.txt

run1:
	./$(PROG1) < input.txt

test3:
	./$(PROG2) < test1.txt

test4:
	./$(PROG2) < test2.txt

run2:
	./$(PROG2) < input.txt
