PROG1 = part1.lua
PROG2 = part2.lua

test2:
	./$(PROG2) < test1.txt
	./$(PROG2) < test2.txt
	./$(PROG2) < test3.txt
	./$(PROG2) < test4.txt
	./$(PROG2) < test5.txt
	./$(PROG2) < test6.txt

run2:
	./$(PROG2) < input.txt

run1:
	./$(PROG1) < input.txt
test1:
	./$(PROG1) < test1.txt
