PROG1 = part1.zsh
PROG2 = part2.zsh

default: run2

test1:
	./$(PROG1) < test1.txt
	./$(PROG1) < test2.txt

run1:
	./$(PROG1) < input.txt

test2:
	./$(PROG2) < test3.txt

run2:
	./$(PROG2) < input.txt
