PROG1 = part1.r
PROG2 = part2.r

default: test2

test1:
	chmod +x $(PROG1)
	./$(PROG1) < test1.txt

test2:
	chmod +x $(PROG2)
	./$(PROG2) < test1.txt

run1:
	chmod +x $(PROG1)
	./$(PROG1) < input.txt

run2:
	chmod +x $(PROG2)
	./$(PROG2) < input.txt

